# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_product_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='persons',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_option',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
    ]
